In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [5]:
dataset=pd.read_csv('Position_Salaries.csv')   #i have to redict salary based on 
#print(dataset)
X=dataset.iloc[:,1:-1].values
Y=dataset.iloc[:,-1].values
print(X)  #array
#if dummy var and 0 ,1 also same as other 0,1 no nned to apply feature scaling 
print(Y) #vector-->ye nned to shape it to array
#coz hume fetire scaling x,y me krni hai x array hai toy bhi aarray ho
Y=Y.reshape(len(Y),1)
print(Y)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]
[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [7]:
#featrre scaling krna padega 
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()  # 2diff req as dono ka mean etc alag alaga hoga
X=sc_X.fit_transform(X)
sc_Y=StandardScaler()
Y=sc_Y.fit_transform(Y)
print(X)
print(Y)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]
[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


In [8]:
from sklearn.svm import SVR
regressor=SVR(kernel= 'rbf')
regressor.fit(X,Y)  #model built and added to data



C:\Users\LENOVO L 340  7LIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [11]:
sc_Y.inverse_transform(regressor.predict(sc_X.transform([[6.5,]])).reshape(-1,1))  #saleed tst data

TypeError: 'numpy.ndarray' object is not callable