In [14]:
#ann can be used both for classfication and etc.
#different datatype se result draw krna hai 
#different data se whether person exited from bank or not 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [15]:
tf.__version__

'2.13.0'

In [16]:
detaset=pd.read_csv('Churn_Modelling.csv')
X=detaset.iloc[:,3:-1].values
Y=detaset.iloc[:,-1].values
print(X)  #matrix of features 
print(Y)  #vector


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(Y)

In [18]:
#genre wala encode 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [20]:
#hot encoding fro country
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=0)
#eature scaling krna hoga dl me 


In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [27]:
#initlaose the ann
ann=tf.keras.models.Sequential()  #keras 


In [30]:
#input layer add
ann.add(tf.keras.layers.Dense(units=6,activation= 'relu'))

In [31]:
#change to see which one gives mst accurabcy   acivation function
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))  #second layer 


In [32]:
#output layer 
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))  #output layer outpotu 0,1 


In [34]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])  #non binary me catergorical crossentriopy

In [35]:
#train ann
ann.fit(X_train,Y_train,batch_size= 32,epochs=100)


Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5165 - accuracy: 0.7949
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4618 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4457 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4369 - accuracy: 0.7962
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4310 - accuracy: 0.7970
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4243 - accuracy: 0.7991
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4153 - accuracy: 0.8033
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8090
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3928 - accuracy: 0.8133
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3844 - accura

In [44]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)   #france nhi 1 0 0  600=600   values wuae hke waise hi bas data original
#probabailty return hogi left or not ki
#print(tt)

ValueError: X has 12 features, but StandardScaler is expecting 13 features as input.