# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np #type alias it
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset=pd.read_csv('/Data.csv') #but where is th data pandas change csv to table?
#independ var matrix
x= dataset.iloc[:,:-1].values  #locate indexes of col and row -->all rows all cols leaving last -1 is the last col upper boundexcludded allc ols excluding last one lelo
#dep var vector
y= dataset.iloc[:,-1].values#take all rows  and not all cold



FileNotFoundError: [Errno 2] No such file or directory: '/Data.csv'

In [ ]:
print(x)

In [11]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
#empty spaces in dep vars  replace the missing with avg :classic methd to handle missing data
#we will use sktlearn to get avg
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy= 'mean')  #relae all missing by mean of feature itself

#add it to put data
imputer.fit(x[:,1:3])  #all only numeric cols 0 pr letters the 2 excluded fit it to cols that have null celss
x[:,1:3]=imputer.transform(x[:,1:3]) #cols of x where we want to replace


In [ ]:
print(x)

## Encoding categorical data

### Encoding the Independent Variable

In [15]:
#france germny spain ko change
from sklearn.compose import ColumnTransformer  #3package class
from sklearn.preprocessing import OneHotEncoder

#jis col me apply
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))  #numpy assary ke form me nhi krta return isliye np.




In [16]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)  #y bhi vector hai ye bhi vecor krta hai not numpay arry

In [18]:
print(y) #yes no

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
#returns 4 sets
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=1)  #seeding



In [20]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

In [ ]:
print(y_train)

In [ ]:
print(y_test)

## Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])  #jin pr scale lahgana hai
X_test[:,3:]=sc.transform(X_test[:,3:])

In [22]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [24]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
